### ISSUE TITLE
Input error for `Eukaryotic binning Snakefile`

### ISSUE THREAD

**Issue by susheelbhanu** [Mass23/NOMIS_ENSEMBLE#13]
@michoug 

-  line #278 has a directory as input in the Euk binning Snakefile
- Leads to errors, 'cos snakemake doesn't take folders as input

- Please add a file that is typically found in the folder to the line so we can use the the `dirname` variable.

**Comment by michoug** [comment]
Yes, it worked for me but I'm aware of this issue.
I'll create a dummy file to resolve it
